FROM golang:1.22-alpine

RUN apk add --no-cache git ca-certificates curl && \
    go install github.com/cosmtrek/air@latest

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
